version: v0
tags: initial-config classes[]
datasets:
  soil: /some/path.hdf5
  pv:
  npv:
  ash+char:
  snow+ice:
  water:
simulation:
  n_components: [1,5]
  n_classes_in_subsets: 3
  alpha: 0.3
  min_frac: 0.1
  alpha_uniform_low: 0.1
  alpha_uniform_high: 10.
  white_noise: 0.0001
  noise-file: example.csv
subsample:
  test-fraction: 0.2
  selected-method: convex-hull
  convex-hull:
    num_pc: 1
    n_samples: 10
    qhull_options:
  kmeans:
    num_pc: 1
    n_samples: 10
    init:
    n_init:
    max_iter:
    tol:
    random_state:
    algorithm:
  kmedoids:
    num_pc: 1
    n_samples: 10
    metric:
    method:
    init:
    max_iter:
    random_state:
  lhs:
    num_pc: 1
    n_samples: 10
    hypercubes_per_dimension: 3
    samples_per_hypercube: 3
dataloader:
  percent-static-data: 0.5
