version: v0
tags: initial-config classes[]
drop-bands-wavelengths: # needs to be a list of tuples
  - [400, 500] # for one-band items
  - [1000, 1200]
datasets:
  soil:
    - /some/path.hdf5
    - /some/path.hdf5
  pv:
    - /some/path.hdf5
  npv:
  ash+char:
  snow+ice:
  water:
ood-test-set: /some/path.hdf5
simulation:
  n_components:
    soil: [1,2,3]
    pv: [1,2,3]
    npv: [1,2,3,4,5]
  n_classes_in_subsets: 3
  alpha: 0.3
  min_frac: 0.1
  alpha_uniform_low: 0.1
  alpha_uniform_high: 10.
  white_noise: 0.0001
  noise_scalar: 
  noise_covariance_csv: static/spectral_noise_covariances.csv
  return_fractions: false
  glint_upper_scalar:
  glint_lower_scalar:
  forced_fraction_test_set:
    soil: [[0.01, 0.05], [0.05, 0.10], [0.10, 0.15], [0.15, 0.25], [0.25, 0.50]]
    pv:
    npv:
    ash+char:
    snow+ice:
    water:
subsample:
  test-fraction: 0.2
  selected-method: convex-hull
  file-specific:
    /some/path.hdf5:
      kmedoids:
        num_pc: 5
        n_samples: 200
  convex-hull:
    num_pc: 1
    n_samples: 10
    qhull_options:
  kmeans:
    num_pc: 1
    n_samples: 10
    init:
    n_init:
    max_iter:
    tol:
    random_state:
    algorithm:
  kmedoids:
    num_pc: 1
    n_samples: 10
    metric:
    method:
    init:
    max_iter:
    random_state:
    metric: mahalanobis
  lhs:
    num_pc: 1
    n_samples: 10
    hypercubes_per_dimension: 3
    samples_per_hypercube: 3
  random:
    n_samples: 10
dataloader:
  percent-static-data: 0.5
test-scene-urls:
  - https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20250404T194611_2509413_006/EMIT_L2A_RFL_001_20250404T194611_2509413_006.nc
  - https://data.lpdaac.earthdatacloud.nasa.gov/lp-prod-protected/EMITL2ARFL.001/EMIT_L2A_RFL_001_20250421T173332_2511111_018/EMIT_L2A_RFL_001_20250421T173332_2511111_018.nc
