version: v0
tags: initial-config
datasets:
  output-directory: /tmp/
  classes:
    soil:
      - http:example.com
      - http:example.com
      - /some/path
    pv:
      - http:example.com
      - /some/path
    npv:
      - http:example.com
      - /some/path
    ash+char:
      - http:example.com
      - /some/path
    snow+ice:
      - http:example.com
      - /some/path
    water:
      - http:example.com
      - /some/path